# Generated by Django 4.1.7 on 2023-02-26 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='messenger.content'),
        ),
    ]
